[hololens]
package = "holo/lens-sencha-package"

[hololens.sencha]
pkg = "school-cbl-config"

[hololens.input]
root = "sencha-workspace"
files = [
    "workspace.json",
    "ext/**",
    "packages/school-cbl-config/**",
    "packages/slate-cbl-colors/**",
    "packages/slate-theme/**",
]

[hololens.output]
root = "webapp-plugin-builds/school-cbl-config"
merge = "replace"
